### ISSUE TITLE
SE7k (firmware 3.2251) works

### ISSUE THREAD

**Issue by akamming** [tjko/sunspec-monitor#19]
Hi, 

Your script works great with the SE7K (model 3.2251). 

The only thing is you have to add "-m 0" to the commandline, otherwise i get a "Read of Meter 1 block registers failed (device does not support SunSpec?) at /usr/sbin/sunspec-status line 224." 

so i wanted to let you know, so you can add this to the documentation (and maybe fix the needing of -m 0)

keep up the good work!

**Comment by tjko** [comment]
Thanks. I added this in the README.md
