### ISSUE TITLE
Output file in JSON format

### ISSUE THREAD

**Issue by mcmellow** [tjko/sunspec-monitor#3]
Request:

- When using the file output. Use the status-code number instead of status-text.

- A json-file output besides a csv-file output would be very handy to

Thanks in advace

**Comment by tjko** [comment]
I added new  -j  option to select JSON output instead of CSV.  There is now option -n to request numeric output which switched status field to numeric (raw SunSpec value) and time stamp from text to Unix (Epoch) timestamp.

**Comment by mcmellow** [comment]
Thanks very much for your updates.
This looks great at a first glance. I will test it more in details for the coming weeks. 
Well done so far

**Comment by mcmellow** [comment]
The script works great in my situation. Issue is closed
